[Match]
Profile=dms-git
Distribution=arch

[Content]
Packages=
    dms-shell-git
    niri-git

[Build]
SandboxTrees=subprojects/chaotic-aur/chaotic.gpg:/usr/share/pacman/keyrings/chaotic.gpg
             subprojects/chaotic-aur/chaotic-trusted:/usr/share/pacman/keyrings/chaotic-trusted
             repos/chaotic-aur.conf:/etc/pacman.d/chaotic-aur.conf
             repos/chaotic-mirrorlist:/etc/pacman.d/chaotic-mirrorlist
