[Match]
Distribution=arch

[Content]
Packages=
    linux
    linux-firmware
    dosfstools
    squashfs-tools
    base
    bash
    polkit
    vim
    nano
    dbus
    dbus-glib
    glib2
    shadow
    7zip
    unrar
    unzip
    fastfetch
    just
    less
    vim
    git
    plymouth
    zram-generator
    man-db
    man-pages
    sudo
    networkmanager
    bluez
    bluez-utils
    power-profiles-daemon
    iptables
    btrfs-progs
