[Match]
Distribution=arch

[Content]
RemoveFiles=
    /usr/share/applications/qt6ct.desktop

Packages=
    xdg-desktop-portal-gtk
    xdg-desktop-portal-gnome
    matugen
    cava
    cups-pk-helper
    i2c-tools
    qt6ct
    wtype
    kimageformats
    greetd
    satty
