[Match]
Distribution=arch

[Content]
Packages=
    xdg-desktop-portal-gtk
    xdg-desktop-portal-gnome
    matugen
    cava
    cups-pk-helper
    i2c-tools
    wtype
    kimageformats
    greetd
    satty
