[Match]
Distribution=arch

[Content]
Packages=
    dms-shell-niri
    xdg-desktop-portal-gtk
    xdg-desktop-portal-gnome
    matugen
    cava
    cups-pk-helper
    i2c-tools
    qt6ct
    wtype
    kimageformats
    greetd
