[Match]
Distribution=arch

[Content]
Packages=
    gnome-keyring
    podman
    distrobox
    flatpak
    gnome-disk-utility
    udiskie
    nautilus-python
    gvfs
    crun

ExtraTrees=
    subprojects/xdg-terminal-exec-nautilus/xdg-terminal-exec-nautilus.py:/usr/share/nautilus-python/extensions/xdg-terminal-exec-nautilus.py
    cosign.pub:/usr/share/pki/containers/lumaeris.pub
