[Match]
Distribution=arch

[Content]
RemoveFiles=
    /usr/share/applications/avahi-discover.desktop
    /usr/share/applications/bssh.desktop
    /usr/share/applications/bvnc.desktop
    /usr/share/applications/foot-server.desktop
    /usr/share/applications/lstopo.desktop
    /usr/share/applications/qv4l2.desktop
    /usr/share/applications/qvidcap.desktop

Packages=
    gnome-keyring
    podman
    distrobox
    flatpak
    gnome-disk-utility
    udiskie
    nautilus-python
    gvfs
    gvfs-afc
    gvfs-dnssd
    gvfs-gphoto2
    gvfs-mtp
    gvfs-nfs
    gvfs-smb
    crun
    foot
    foot-terminfo
    libnotify
    chezmoi
    qt6-multimedia
    qt6-multimedia-ffmpeg
    steam-devices
    thermald
    adw-gtk-theme

ExtraTrees=
    subprojects/xdg-terminal-exec-nautilus/xdg-terminal-exec-nautilus.py:/usr/share/nautilus-python/extensions/xdg-terminal-exec-nautilus.py
    subprojects/bootc-tools/bootc-db-diff:/usr/bin/bootc-db-diff
