[Match]
Distribution=arch

[Content]
Packages=
    gnome-keyring
    podman
    distrobox
    flatpak
    gnome-disk-utility
    udiskie
    nautilus-python
    gvfs
    crun
    foot
    foot-terminfo
    libnotify
    chezmoi
    qt6-multimedia
    qt6-multimedia-ffmpeg

ExtraTrees=
    subprojects/xdg-terminal-exec-nautilus/xdg-terminal-exec-nautilus.py:/usr/share/nautilus-python/extensions/xdg-terminal-exec-nautilus.py
