[Match]
Distribution=arch

[Content]
Packages=
    mesa
    mesa-utils
    xorg-xwayland
    vulkan-icd-loader
    vulkan-intel
    vulkan-radeon
    vulkan-nouveau
    vulkan-tools
    libglvnd
    qt6-multimedia-ffmpeg
