[Match]
Distribution=arch

[Content]
Packages=
    mesa
    mesa-utils
    xwayland-satellite
    vulkan-icd-loader
    vulkan-intel
    vulkan-radeon
    vulkan-nouveau
    vulkan-tools
    libglvnd
