---
name: Build container image
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "30 06 * * TUE" # 06:30am UTC on tuesday
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

env:
  IMAGE_DESC: "Stargaze"
  IMAGE_KEYWORDS: "bootc,arch,bootcrew"
  IMAGE_LOGO_URL: "https://avatars.githubusercontent.com/u/10499845?s=200&v=4"
  IMAGE_REGISTRY: "ghcr.io/${{ github.repository_owner }}"
  DEFAULT_TAG: "latest"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.brand_name }}-${{ inputs.stream_name }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build and push image
    runs-on: ubuntu-26.04

    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        image_name:
          - stargaze
          - stargaze-nvidia

    steps:
      - name: Prepare environment
        run: |
          # Lowercase the image uri
          echo "IMAGE_REGISTRY=${IMAGE_REGISTRY,,}" >> ${GITHUB_ENV}
          echo "IMAGE_NAME=${{ matrix.image_name }}" >> ${GITHUB_ENV}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - name: Free disk space
        uses: hastd/free-disk-space@68572aeaadb7f76bd408246328e95926323402b5 # v0.1.2
        with:
          exclude: |
            /opt/hostedtoolcache/Python
          skip-if-available: "64G"

      - name: Install just
        run: |
          sudo apt update
          sudo apt install -y just

      # using last known working version of mkosi for working with arch
      - name: Install mkosi
        uses: systemd/mkosi@c4c3d793d0f6f0a2f26895de5ed9382396f36bb5

      - name: Set mkosi.version
        # We need to do this because mkosi.version is not persistent between builds on CI
        run: skopeo list-tags docker://${IMAGE_REGISTRY}/${IMAGE_NAME} | jq --arg date "$(date -u +%Y%m%d)" -r '.Tags[] | select(startswith($date+"."))' | sort -n | tail -1 > mkosi.version

      - name: Render configuration (for debugging)
        run: mkosi cat-config --debug

      - name: Build Image
        run: |
          set -e

          if [[ ${IMAGE_NAME} =~ "nvidia" ]]; then
            profiles="brew,dms,nvidia,bootc"
          else
            profiles="brew,dms,bootc"
          fi

          env CI=true BUILD_PROFILES=${profiles} just build

      - name: Load Image
        run: |
          set -e
          env CI=true BUILD_IMAGE_NAME=${IMAGE_NAME} just load

      - name: Lint Image
        run: |
          set -e
          env BUILD_IMAGE_NAME=${IMAGE_NAME} just lint

      - name: Get Version
        id: getversion
        run: |
          set -e
          echo "image_version=$(cat mkosi.version)" >> "$GITHUB_OUTPUT"

      - name: Rechunk Image
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: |
          set -e
          env CI=true BUILD_IMAGE_NAME=${IMAGE_NAME} just rechunk

      - name: Image Metadata
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: metadata
        with:
          tags: |
            type=raw,value=${{ env.DEFAULT_TAG }}
            type=raw,value=${{ steps.getversion.outputs.image_version }}
            type=sha,enable=${{ github.event_name == 'pull_request' }}
            type=ref,event=pr
          sep-tags: " "

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOGIN_USER: ${{ github.actor }}
        run: |
          echo "${GITHUB_TOKEN}" | podman login -u "${LOGIN_USER}" --password-stdin "ghcr.io"

      - name: Push to GHCR
        if: github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        id: push
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAGS: ${{ steps.metadata.outputs.tags }}
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
          MAX_RETRIES: 3
        run: |
          set -x

          PRIVATE_KEY_FILE="$(mktemp)"
          echo "${SIGNING_SECRET}" > "${PRIVATE_KEY_FILE}"
          trap 'rm -f $PRIVATE_KEY_FILE' EXIT
          sudo mkdir -p "/etc/containers/registries.d/"
          echo -e "docker:\n  ${IMAGE_REGISTRY}:\n    use-sigstore-attachments: true" | sudo tee "/etc/containers/registries.d/${REPOSITORY_OWNER}.yaml"

          log_sum() { echo "$1" >> $GITHUB_STEP_SUMMARY; }
          log_sum '# Push to GHCR result'
          log_sum '```'

          for tag in $IMAGE_TAGS; do
            podman push --compression-format=zstd "localhost/${IMAGE_NAME}:${DEFAULT_TAG}" \
              "${IMAGE_REGISTRY}/${IMAGE_NAME}:${tag}" --sign-passphrase-file=/dev/null \
              --sign-by-sigstore-private-key=${PRIVATE_KEY_FILE} --retry=${MAX_RETRIES}
            log_sum "${IMAGE_REGISTRY}/${IMAGE_NAME}:${tag}"
          done

          log_sum '```'
